//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaStreamingProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class TvShow
    {
        public int ShowID { get; set; }
        public int NetworkID { get; set; }
        public string ShowName { get; set; }
        public Nullable<int> Seasons { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> StartYear { get; set; }
        public Nullable<float> ImdbRating { get; set; }
        public string TvShow_Image_Link { get; set; }
    
        public virtual Network Network { get; set; }
    }
}
